import React, { useEffect, useState, useCallback } from 'react';
import { fetchFinancialTips, fetchBudgets, fetchExpenses } from '../services/api'; // Import fetch functions for budgets and expenses
import Navbar from './Navbar';
import { Alert, Container, Button } from 'react-bootstrap';
import { FiLoader } from 'react-icons/fi';
import { CgEditBlackPoint } from "react-icons/cg";
import { Link } from 'react-router-dom';

const FinancialTips = () => {
  const [tips, setTips] = useState([]);
  const [loading, setLoading] = useState(true);
  const [loadingMessage, setLoadingMessage] = useState('Please wait, we are fetching your personalized financial tips...');
  const [error, setError] = useState('');
  const [theme, setTheme] = useState('light');
  const [reloadOnFirstError, setReloadOnFirstError] = useState(false); // State to trigger reload on first error
  const [lastError, setLastError] = useState(false); // State to track the last error occurrence
  const [hasBudgetsOrExpenses, setHasBudgetsOrExpenses] = useState(false); // State to check if user has budgets or expenses

  useEffect(() => {
    const storedTheme = localStorage.getItem('theme');
    if (storedTheme) {
      setTheme(storedTheme);
    }
  }, []);

  const parseTips = useCallback((response) => {
    const lines = response.split('\n').filter(line => line.trim() !== '');
    return lines.map((line, index) => {
      let type = 'normal';
      let icon = '';

      const keywordToHighlight = 'WASH:';
      if (line.toUpperCase().includes(keywordToHighlight)) {
        type = 'highlighted';
      } else if (line.startsWith('### ')) {
        type = 'section';
        line = line.replace(/### /g, '').trim();
      } else if (line.startsWith('**') && line.endsWith('**')) {
        type = 'bold';
        line = line.replace(/\*\*/g, '').trim();
        icon = getIcon(line);
      } else if (line.startsWith('- **') && line.endsWith('**')) {
        type = 'semiBold';
        line = line.replace(/- \*\*/g, '').replace(/\*\*/g, '').trim();
      } else {
        line = line.replace(/[*-]/g, '').trim();
      }

      return { type, text: line, icon, index };
    });
  }, []);

  const loadTips = useCallback(async () => {
    try {
      setLoading(true);
      setLoadingMessage('Generating tips...');

      const response = await fetchFinancialTips();

      if (!response) {
        throw new Error('Empty response received');
      }

      if (Array.isArray(response) && response.length === 1 && typeof response[0] === 'string') {
        setTips(parseTips(response[0]));
        setLoading(false);
        setError('');
        setLastError(false); // Reset lastError state on successful load
      } else {
        throw new Error('Invalid response format');
      }
    } catch (error) {
      console.error('Failed to load financial tips:', error);
      setError('Failed to load financial tips');
      setLoading(false);

      // Trigger auto-reload only once on first error occurrence
      if (!reloadOnFirstError) {
        setReloadOnFirstError(true);
        setLoadingMessage(`Failed to load tips. Retrying in 5 seconds...`);

        window.location.reload();
      }

      // Set lastError to true to indicate last error occurred
      setLastError(true);
    }
  }, [parseTips, reloadOnFirstError]);

  const checkBudgetsAndExpenses = useCallback(async () => {
    try {
      const budgets = await fetchBudgets();
      const expenses = await fetchExpenses();
      
      if (budgets.length > 0 || expenses.length > 0) {
        setHasBudgetsOrExpenses(true);
        loadTips();
      } else {
        setLoading(false);
        setTips([]);
        setLoading(false);
        setError('To receive personalized financial tips, please set your budget and add some expenses.');
        setHasBudgetsOrExpenses(false);
      }
    } catch (error) {
      console.error('Failed to fetch budgets or expenses:', error);
      setError('Failed to fetch budgets or expenses');
      setLoading(false);
    }
  }, [loadTips]);

  useEffect(() => {
    checkBudgetsAndExpenses();
  }, [checkBudgetsAndExpenses]);

  const getIcon = (title) => {
    switch (title.toUpperCase()) {
      // Icons mapping...
    }
  };

  const handleReload = () => {
    setReloadOnFirstError(false); // Allow reload on user-triggered action
    window.location.reload();
  };

  const renderTips = () => {
    if (loading) {
      return (
        <div className="text-center">
          <p>{loadingMessage}</p>
          <div className="mt-4">
            <FiLoader className="animate-spin mx-auto" />
          </div>
          <Alert variant="info" className="mt-4">Note: These tips are generated by AI and may not always be perfectly accurate.</Alert>
          <Alert className="mt-4">This might take a few moments.</Alert>
        </div>
      );
    }

    if (error && !lastError) { // Display error only if it's not the last error
      return (
        <div className="text-center mt-4">
          <Alert variant="danger">
            Error: {error} 
            {error.includes('budget') && (
              <>
                &nbsp;
                <div className="mt-3">
                <Link to="/budgets" className="inline-block px-4 py-2 text-white bg-blue-500 border border-transparent rounded-md shadow-sm hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">
                  Set your budget here.
                </Link>
              </div>

              </>
            )}
          </Alert>
          {hasBudgetsOrExpenses && (
            <Button variant="primary" onClick={handleReload} className="mt-3">
              Reload Tips
            </Button>
          )}
        </div>
      );
    }

    if (tips.length === 0) {
      return <Alert variant="info" className="text-center mt-4">Fetching personalized financial tips...</Alert>;
    }

    return (
      <div className="mt-4">
        <div className="text-center mb-4">
          <Alert variant="info" className='text-gray-400'>Note: These tips are generated by AI and may not always be perfectly accurate.</Alert>
        </div>
        {tips.map(({ text, type, icon, index }) => (
          <div key={index} className={`mb-4 p-4 rounded-lg shadow-lg transition-transform transform hover:scale-105 ${theme === 'dark' ? 'bg-gray-800 text-white border border-white' : 'bg-white text-gray-800'} text-center`}>
            {type === 'section' && (
              <div className="text-2xl font-bold mb-2 text-blue-600">{text}</div>
            )}
            {type === 'highlighted' && (
              <div className="font-bold text-red-600">{text}</div>
            )}
            {type !== 'section' && type !== 'highlighted' && (
              <div className={`text-base ${type === 'bold' ? 'font-bold text-blue-600' : ''} ${type === 'semiBold' ? 'font-semibold text-green-500' : ''} ${type === 'normal' ? (theme === 'dark' ? 'text-white' : 'text-gray-800') : ''}`}>
                {icon && <span className="mr-3">{icon}</span>}
                {type === 'section' ? text : (
                  
                  <ul className="list-inside text-left mx-auto">
                    <CgEditBlackPoint className='mb-3' />
                    <li className="font-bold">{text}</li>
                  </ul>
                )}
              </div>
            )}
          </div>
        ))}
      </div>
    );
  };

  return (
    <>
      <Navbar />
      <Container className="d-flex justify-content-center align-items-center" fluid>
        <div className={`rounded-lg shadow-md p-4 mx-auto my-20 mt-24 ${theme === 'light' ? 'bg-white text-gray-900' : 'bg-gray-800 text-white'} max-w-screen-lg`}>
          <h1 className="text-4xl font-bold mb-4 text-center">Personalized Financial Tips 💡</h1>
          {renderTips()}
        </div>
      </Container>
    </>
  );
};

export default FinancialTips;
