name: Build and deploy Node.js app to Azure Web App - pennywise

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'      

      - name: Install npm packages - server
        run: |
          cd server
          npm install       
      
      - name: Install npm packages, build then copy files - client
        run: |
          cd client
          npm install
          npm run build
          mkdir -p ../server/public
          cp -r ./build ../server/public
            
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: mern-app
          path: server

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: mern-app

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_844A067A04AB4AA3B010CF8B71C9BD28 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8554BAD55AD547D2929A9B5A6759749F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_278B1CB9B5F94FC2A9A1EE7FE6A56862 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'pennywise'
          slot-name: 'Production'
          package: .

